server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Serve the APK with the correct MIME type for Android install.
    location /greffe-renale.apk {
        types { application/vnd.android.package-archive apk; }
        add_header Content-Disposition 'attachment; filename="greffe-renale.apk"';
    }
}
